######################################################################
##
## Copyright (C) 2004,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:   Makefile
##
## $Id: Makefile 9085 2006-07-19 10:41:58Z ska $
##
######################################################################
SUBDIRS   =
TARGET    = loader
HEADERS   = ../../include/file_handling.h
INCLUDES  = -I../../include -I../../../lib/include
OBJS      = main.o file_handling.o
EXTRA_CLEAN=example/*~

include ../../../Rules_SDL.mk
