######################################################################
##
## Copyright (C) 2004,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:   Makefile
##
## $Id: Makefile 1104 2005-01-16 05:59:19Z ska $
##
######################################################################
SUBDIRS   =
TARGET    = creator
HEADERS   =
INCLUDES  = -I../../include -I../../../lib/include
OBJS      = main.o utils.o
EXTRA_CLEAN=example/*~

include ../../../Rules_SDL.mk
