######################################################################
##
## Copyright (C) 2004,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:   Makefile for the event handler
##
## $Id: Makefile 637 2004-09-19 16:26:03Z ska $
##
######################################################################
TARGET    = eventmap
OBJS      = main.o
LDLIBS    = -lSDL -lSDL_image

include ../../../Rules_SDL.mk
