######################################################################
##
## Copyright (C) 2004,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:   Makefile for the tilecreator
##
## $Id: Makefile 2174 2005-03-18 07:00:30Z ska $
##
######################################################################
TARGET    = imgbound
OBJS      = main.o
LDLIBS    = -lSDL -lSDL_image

include ../../../Rules_SDL.mk
