######################################################################
##
## Copyright (C) 2004,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:   Makefile
##
## $Id: Makefile 498 2004-08-22 08:14:35Z ska $
##
######################################################################
SUBDIRS   = level_creator level_loader level_packer

include ../../Rules_SDL.mk
